export const stackData = [
    { src: "/htmlIcon.svg", name: "HTML" },
    { src: "/cssIcon.svg", name: "CSS" },
    { src: "/jsIcon.svg", name: "JavaScript" },
    { src: "/typescriptIcon.svg", name: "TypeScript" },
    { src: "/reactIcon.svg", name: "React" },
    { src: "/reactIcon.svg", name: "React-Native" },
    { src: "/nextjsIcon.svg", name: "Next.Js" },
    { src: "/reduxIcon.svg", name: "Redux" },
    { src: "/sassIcon.svg", name: "Sass" },
    { src: "/tailwindIcon.svg", name: "Tailwind" },
    { src: "/nodejsIcon.svg", name: "Node.Js" },
    { src: "/expressjsIcon.svg", name: "Express" },
    { src: "/mongodbIcon.svg", name: "Mongo DB" },
    { src: "/web3Icon.svg", name: "Web3" },
    { src: "/awsIcon.svg", name: "AWS" },
    { src: "/firebaseIcon.svg", name: "Firebase" },
    { src: "/gitIcon.svg", name: "Git" },
    { src: "/githubIcon.svg", name: "Github" },
    { src: "/npmIcon.svg", name: "npm" },
    { src: "/dockerIcon.svg", name: "Docker" },
    { src: "/pythonIcon.svg", name: "Python" },
    { src: "/figmaIcon.svg", name: "Figma" },
    { src: "/adobexdIcon.svg", name: "Adobe XD" },
  ];

  export const projectsData = [
    {
      name: "Portfolio",
      description: "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
      src: "/demo.png",
      liveLink: "",
      githubLink: "",
    },
    {
      name: "Portfolio",
      description: "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
      src: "/demo.png",
      liveLink: "",
      githubLink: "",
    },{
      name: "Portfolio",
      description: "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
      src: "/demo.png",
      liveLink: "",
      githubLink: "",
    },{
      name: "Portfolio",
      description: "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
      src: "/demo.png",
      liveLink: "",
      githubLink: "",
    },{
      name: "Portfolio",
      description: "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
      src: "/demo.png",
      liveLink: "",
      githubLink: "",
    },{
      name: "Portfolio",
      description: "This is sample project description random things are here in description This is sample project lorem ipsum generator for dummy content",
      src: "/demo.png",
      liveLink: "",
      githubLink: "",
    },
  ]
